# -*- coding: utf-8 -*-
"""
Created on Thu May 15 17:17:44 2014

@author: isn
"""

TexteJoueurEau = {1:"C'est pitoyable!", 2:"Tu vises trop mal!", 3:"Ceci n'est pas un message subliminale.", 4:"Mecreant, chenapant! Jamais tu ne me battras!", 5:"Meme ma LED joue mieux que toi!", 6:"Ah, toi aussi tu chasse le requin?", 7:"Ne viens pas me faire croire que tu l'as fais expres!", 8:"Mais dis moi, t'es trop nul.", 9:"Tu es sur que tu ne veux pas echanger ta place avec ma LED?", 10:"Oh, quel dommage, c'est rate..."}
TexteJoueurImpact = {1:"N'espère pas m'en toucher un autre!", 2:"Meme pas mal!", 3:"Aie!", 4:"Enfin", 5:"Mon pauvre vieux, tu crois vraiment pouvoir gagner la guerre avec ca? ...", 6:"M'en fiche, j'ai les meilleurs mecaniciens du monde!", 7:"Petit joueur...", 8:"I will survive!!!!", 9:"Il n'est pas encore coule!", 10:"Comment oses tu tuer mes soldats?!?"}
TexteJoueurCoul = {1:"Comment oses-tu couler mes navires?!?", 2:"La guerre n'est toujours pas finie!", 3:"Cela ne sert à rien, tu perdras cette guerre, quoi qu'il arrive.", 4:"Un de perdu, dix de retrouves. Medite sur ces paroles.", 5:"Il m'a coute des milliards celui la, tu n'as pas honte!?!", 6:"La vie ne se resume pas a un simple navire...", 7:"Il rejoindra peut etre le Titanic celui la.", 8:"Je suis bon joueur, je ne m'enerverai pas.", 9:"Je suis l'ordinateur, le programme, Dieu, je peux faire revivre mes navires, MOUAHAHA!!!", 10:"J'en ai encore tellement en reserve, tu esperes quoi avec ca? "}
TexteJoueurNul = {1:"LOL!", 2:"Tu n'es pas deja assez en retard comme ca?", 3:"Pourquoi je joue contre toi? ...", 4:"Tu en deviens deprimant...", 5:"Tu essais de toucher les obus que tu envois?", 6:"Je crois bien que... bah tu es nul.", 7:"Oh mon Dieu, tu m'as touche! Non je rigole, c'est tes obus que tu touches...", 8:"A la peche au moules moules...", 9:"Et tu te consideres comme commandant? ...", 10:"Tu es sur que tu n'es pas un ordinateur mal programme?"}
TexteIAEau = {1:"Tu as deplace tes navires, tu triches!", 2:"Je l'ai fais expres.", 3:"Je chasse le requin!", 4:"Avoue, je te fais peur!", 5:"Le prochain touchera tes navires!", 6:"Desole, j'etais au telephone, je ne visais pas.", 7:"Non, tu n'as rien vus!", 8:"Je tente de me mettre a ton niveau", 9:"Plouf!", 10:"Pour combien tu me donnes tes coordonees?"}
TexteIAImpact = {1:"I see you...", 2:"Veux-tu visiter le fond des oceans? Je t'y envoie tout de suite!", 3:"Brule, brule, bruuuule!", 4:"Et BOOM!", 5:"Tu devrais revoir tes navires, certains on des fuites, AH AH AH!", 6:"Mmmh, pas tres resistants tes navires, vire ton ingenieur.", 7:"Oh le beau bateau qui brule.", 8:"Ce que tu ne sais pas, c'est que j'ai acces a tes coordonnees, hin hin hin...", 9:"Mes espions ont bien fais leur travail.", 10:"Trop facile, Ah Ah Ah!!!"}
TexteIACoul = {1:"Tu n'esperais quand meme pas me détruire mes navires avec ca?", 2:"Et un de moins, c'est si facile...", 3:"Je suis le maitre du mooooonde!!!", 4:"Il etait un petit navire...", 5:"Il etait si moche, je me suis sentie oblige, desole", 6:"A mort les anglois!!!", 7:"Tu m'enverra une carte postal du fond des oceans?", 8:"Etre ou ne pas etre, telle est la question. Toi, tu n'es plus, Ah Ah!", 9:"Mes marins sont mort de rire, tu m'expliques pourquoi?", 10:"Et un de moins en plus, euh de moins, enfin... enfin tu m'as compris!!"}